### ISSUE TITLE
Error: Shape input of size 7680

### ISSUE THREAD

**Issue by khawar-islam** [ofsoundof/LocalViT#3]
@ofsoundof Thank you for your work

Actually, there are two PVT V1 and V2, PVTV2 is better than PVT V1. I am implementing your idea in PVT V2 but getting some errors. Otherwise, my network works fine, I made some changes to it. The error is pointing into  `if self.sr_ratio == 1:`
Remember, my image size is 112, and patch_size=8 other than that everything is same
 
Your Block

```
class Block(nn.Module):

    def __init__(self, dim, num_heads, mlp_ratio=4., qkv_bias=False, qk_scale=None, drop=0., attn_drop=0.,
                 drop_path=0., act_layer=nn.GELU, norm_layer=nn.LayerNorm, sr_ratio=1):
        super().__init__()
        self.sr_ratio = sr_ratio
        self.norm1 = norm_layer(dim)
        self.attn = Attention(
            dim,
            num_heads=num_heads, qkv_bias=qkv_bias, qk_scale=qk_scale,
            attn_drop=attn_drop, proj_drop=drop, sr_ratio=sr_ratio)
        # NOTE: drop path for stochastic depth, we shall see if this is better than dropout here
        self.drop_path = DropPath(drop_path) if drop_path > 0. else nn.Identity()
        # self.norm2 = norm_layer(dim)
        # mlp_hidden_dim = int(dim * mlp_ratio)
        # self.mlp = Mlp(in_features=dim, hidden_features=mlp_hidden_dim, act_layer=act_layer, drop=drop)
        self.conv = LocalityFeedForward(dim, dim, 1, mlp_ratio, reduction=dim)

    def forward(self, x, H, W):
        batch_size, num_token, embed_dim = x.shape  # (B, 197, dim)
        patch_size = int(math.sqrt(num_token))

        x = x + self.drop_path(self.attn(self.norm1(x), H, W))
        # x = x + self.drop_path(self.mlp(self.norm2(x)))

        if self.sr_ratio == 1:
            cls_token, x = torch.split(x, [1, num_token - 1], dim=1)  # (B, 1, dim), (B, 196, dim)
            # print(cls_token.shape, x.shape)
            x = x.transpose(1, 2).view(batch_size, embed_dim, patch_size, patch_size)  # (B, dim, 14, 14)
            x = self.conv(x).flatten(2).transpose(1, 2)  # (B, 196, dim)
            x = torch.cat([cls_token, x], dim=1)
        else:
            x = x.transpose(1, 2).view(batch_size, embed_dim, patch_size, patch_size)  # (B, dim, 14, 14)
            x = self.conv(x).flatten(2).transpose(1, 2)  # (B, 196, dim)
        return x
```

```
Traceback (most recent call last):
  File "/media/khawar/HDD_Khawar/facerectransformer-main/code/train.py", line 231, in <module>
    print_per_layer_stat=True, verbose=True)
  File "/home/khawar/anaconda3/envs/RSC/lib/python3.7/site-packages/ptflops/flops_counter.py", line 43, in get_model_complexity_info
    _ = flops_model(batch)
  File "/home/khawar/anaconda3/envs/RSC/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/khawar/HDD_Khawar/facerectransformer-main/code/vit_pytorch/pvt_v2.py", line 372, in forward
    x = self.forward_features(x)
  File "/media/khawar/HDD_Khawar/facerectransformer-main/code/vit_pytorch/pvt_v2.py", line 364, in forward_features
    x = blk(x, H, W)
  File "/home/khawar/anaconda3/envs/RSC/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/khawar/HDD_Khawar/facerectransformer-main/code/vit_pytorch/pvt_v2.py", line 212, in forward
    x = x.transpose(1, 2).view(batch_size, embed_dim, patch_size, patch_size)  # (B, dim, 14, 14)
RuntimeError: shape '[1, 512, 4, 4]' is invalid for input of size 7680
```

**Comment by ofsoundof** [comment]
Hi @khawar512 ,
Thanks for your interest in our work. This is a problem due to the inappropriate reshaping and dimension changing operations. To debug the code, it is helpful to analyze the dimension of the tensors in the forward function. You can do so by the changing the comments following each line. I believe it will be much easier for you to find the bug and also better for me to help you once you have done that.

**Comment by khawar-islam** [comment]
Thank you @ofsoundof
